- name: Checkout Documentation Generator Repo
        uses: actions/checkout@v4
        with:
          repository: 'ssrin72/docAider-gemini'
          ref: 'main'
          token: ${{ secrets.PAT_FOR_DOC_GENERATOR }}
          path: doc-generator-repo
          submodules: recursive # <-- ADD THIS LINE